# Generated by Django 6.1.1 on 2026-09-25 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('logo', models.URLField(blank=True)),
                ('cover_image', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Communities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CommunityModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('home', 'Home'), ('members', 'Members'), ('events', 'Events'), ('businesses', 'Businesses'), ('discussions', 'Discussions'), ('shop', 'Shop'), ('jobs', 'Jobs'), ('projects', 'Projects'), ('resources', 'Resources')], max_length=40)),
                ('is_active', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('coming_soon_message', models.CharField(blank=True, default='Coming soon', max_length=200)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='communities.community')),
            ],
            options={
                'ordering': ['order', 'key'],
                'unique_together': {('community', 'key')},
            },
        ),
    ]
